gen-summary to also generate rx-lost/sec

diff --git a/iperf/bin/this-run b/iperf/bin/this-run
--- a/iperf/bin/this-run
+++ b/iperf/bin/this-run
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# Usage: this-run [-l LABEL]
-# Ex: this-run -l MY-RUN
+# Usage: this-run [--label LABEL]
+# Ex: this-run --label MY-RUN
 #  1. Invoke run.sh
 #  2. Move the results to under current dir i.e ./run-MY-RUN-2021-11-27-05:02:26/
 #  4. Generate summary :
@@ -16,20 +16,49 @@ if [ -f ./thislabel ]; then
     LABEL=$(cat ./thislabel)
 fi
 
-while getopts "l:" option; do
-    case "${option}" in
-        l) 
-            LABEL=${OPTARG}
+
+function f_help {
+    me=`basename "$0"` 
+    echo Usage: $me "[--label <day-label>]"
+}
+
+
+LABEL=""
+longopts="label:,help"
+opts=$(getopt -q -o "" --longoptions "$longopts" -n "getopt.sh" -- "$@");
+if [ $? -ne 0 ]; then
+    echo "Unrecognized option specified"
+    exit
+fi
+eval set -- "$opts";
+while true; do
+    case "$1" in
+        --label)
+            shift;
+            LABEL=$1
+            shift;
             ;;
-        :)
-            echo "Error: -${OPTARG} requires an argument."
+        --)
+            shift;
+            break
+            ;;
+        --help)
+            shift;
+            f_help
             exit
             ;;
-        *)  # If unknown (any other) option:
+
+        *)
+            echo "Invalid option: $1"
             exit
-            ;;
     esac
 done
+
+if [ "$LABEL" == "" ]; then
+    f_help
+    exit
+
+fi
 
 DIR="run-${LABEL}-$(date "+%Y-%m-%d-%T")"
 #DIR="run-std-00-2022-06-12-23:08:43"
